fetch:
  - "https://raw.githubusercontent.com/Ivan-Istomin/theoceanx-python/master/.codeclimate.yml"
plugins:
  editorconfig:
    enabled: true
    channel: beta
  pep8:
    enabled: true
  sonar-python:
    enabled: true
engines:
 duplication:
   enabled: true
   config:
     languages:
     - python
 rubocop:
   enabled: true
ratings:
 paths:
   - "**.py"
version: "2" 
checks:
  similar-code:
    config:
      threshold: #overriding will affect all languages
  identical-code:
    config:
      threshold: #overriding will affect all languages
exclude_paths:
  - "theoceanx-python/__pycache__"
  - "tests/__pycache__"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"